Update UGDG for delete debt
AY2223S1-CS2103T-W13-3/tp pull request #126
Opened 2022-10-18 14:19 UTC by WR3nd3

Updated DG Use Cases. Note Use Case numbers are currently not in order and should be finalised after most use cases for the features are drafted.

The command prefix for delete debt will be changed to deletedebts from deletedebt. Refactoring will be conducted after the relevant pull-requests are concluded.

2022-10-19 19:42 UTC, waynezsy submitted a review, later dismissed

2022-10-19 19:42 UTC, waynezsy commented on docs/UserGuide.md
> +Format: `deletedebts <person index> debt/1 3 4`
debt/ `<debt index...>` ?

2022-10-20 13:09 UTC, lyuting47 approved these changes
LGTM

2022-10-20 13:38 UTC, waynezsy approved these changes
LGTM

2022-10-20 13:38 UTC, merged

2022-10-20 13:38 UTC, lyuting47 requested changes

2022-10-20 13:38 UTC, lyuting47 commented on docs/DeveloperGuide.md
> +* 3a. The given indexes are invalid.
"indexes" -> "person or debt indices" to better illustrate that either one may cause an error?