Add splitdebt to DG
AY2223S1-CS2103T-W13-3/tp pull request #327
Opened 2022-11-06 14:41 UTC by WR3nd3

2022-11-06 14:49 UTC, lyuting47 approved these changes
LGTM

2022-11-06 15:57 UTC, waynezsy requested changes

2022-11-06 15:57 UTC, waynezsy commented on docs/DeveloperGuide.md
> +Some commands such as marking debts as paid, or possible future extensions such as editing a debt, may require modifying a `Debt` object in the `DebtList` of a `Person`. To ensure that modifying this
imo shorten this part since you are merely copying from adddebt

2022-11-06 15:57 UTC, waynezsy commented on docs/DeveloperGuide.md
> +To enable the user to retroactively add a `Debt` that is backdated, the `SplitDebtCommandParser` can take in optional `<date>` and `<time>` parameters. By making these parameters optional, a default
this one is also copied, can shorten or remove since it does not differ from adddebt.

2022-11-07 04:30 UTC, waynezsy approved these changes
LGTM

2022-11-07 05:23 UTC, lyuting47 approved these changes
LGTM

2022-11-07 05:23 UTC, merged